server:
  port: 12001

spring:
  profiles:
    active: pc
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
demo:
  title: Demo-系统
  description: 自己的系统
  author: kangJia
  homepage: https://ikangjia.cn/
  net-name: 林深时觉寒 || 极客猫 || Limor
  email: ikangjia.cn@outlook.com
  version: 0.0.1
  copyrightYear: 2022
logging:
  level:
    cn.ikangjia.demo.mapper: debug

mybatis-plus:
  global-config:
    banner: off
    db-config:
      id-type: auto
