server:
  port: 12001

spring:
  profiles:
    active: pc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db_demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
demo:
  title: Demo-系统
  description: 自己的系统
  author: kangJia
  homepage: https://ikangjia.cn/
  net-name: 林深时觉寒 || 极客猫 || Limor
  email: ikangjia.cn@outlook.com
  version: 0.0.1
  copyrightYear: 2022
logging:
  level:
    cn.ikangjia.demo.mapper: debug

mybatis-plus:
  global-config:
    banner: off
    db-config:
      id-type: auto
